### PR TITLE
Added support for mocha-junit-reporter

### PR DESCRIPTION
**Pull request by drazisil**
https://www.npmjs.com/package/mocha-junit-reporter

mocha-junit-reporter is a very nice reporter that outputs JUnit xml results that can be automatically picked up by several CI systems.

Thank you for this, very nifty! :)

### CODE REVIEW

**Comment by glenjamin** [comment]
This is just adding into the test suite, as things already worked?

I'm inclined not to merge this as I don't think it really changes much - I'm open to being convinced otherwise though.

**Comment by drazisil** [comment]
On further reflection, I'm not sure it actually did work, as I ended up with a blank file. Let me get back to you on that. :)

**Comment by drazisil** [comment]
I'll close this, but where would I look to see if it's comparing a blank output file? It's being generated, but nothing in it. The spec output is fine.

**Comment by glenjamin** [comment]
I think it's likely you'll need to pass `reporterOptions` to that reporter rather than using the output redirection, as it has it's own way of picking the file to write to. There are examples of how to do this in the README.

For this scenario, I use the built-in xunit reporter like so:

```sh
mocha -R mocha-multi -O spec=-,xunit=$TARGET
```

This gives me spec output to stdout and xunit to my desired TARGET file.

**Pull request closed without merging**
