### PR TITLE
mocha4 node6 and eslint

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@glenjamin now we're on node 6 and above we can use all the hot new features!

`plugin:node/recommended` makes sure we don't use any features that arn't in node 6

**Comment by glenjamin** [comment]
I'm not sure this is worth it, what's been gained?

**Comment by graingert** [comment]
@glenjamin eslint is great for finding errors before deployment. It also allows a consistent code style for cpntributors

**Comment by graingert** [comment]
@glenjamin also people spent a lot of time and effort specifying and implementing the new JS features, it's a shame not to use them.

**Comment by graingert** [comment]
@glenjamin can you merge and release #32 or #29 ?

**Comment by glenjamin** [comment]
Have merged #29 for now, no quibbles there.

--------

eslint in general I'm a big fan of (I have even contributed rules to core).

I didn't realise this project didn't have an eslint setup at all, it must pre-date me using it widely. I agree it's worth adding eslint and setting up the rules to catch common errors.

--------

ES6 I'm also generally a fan of for new work.

I'm not sure it's useful to wholesale convert a project to use ES6 features when the existing code is correct using ES5 features, at best it'll do the same thing, at worst a subtle mistake could be introduced (from what I can see in the diff, no mistakes appear to have been made). It also messes up the git blame history for individual lines.

In the case of this library, it's not really under active development so there's even less to be gained than if this was an upgrade as a precursor to doing a bunch more work.

------------

I'd be open to adding eslint with a ruleset focused on common errors (like the builtin recommended set) and also allowing ES6 syntax to be used.
I don't think ES6 syntax should be required or converted.

**Comment by graingert** [comment]
> than if this was an upgrade as a precursor to doing a bunch more work.

I was actually planning on fixing the rest of the errors and having a go at the two outstanding todos. I find it a lot easier to work on Airbnb code-bases.

**Comment by glenjamin** [comment]
> I was actually planning on fixing the rest of the errors and having a go at the two outstanding todos. I find it a lot easier to work on Airbnb code-bases.

Then in that case, I'm open to this 😄 

Can you remove the `lint` step from `npm test` and instead add it as a separate line item on travis? I'd rather they both always ran.

My previous experience of airbnb was that it was really picky about minor style things, but I guess the `-base` package doesn't include these rules as it looks like my original style has mostly passed?

I'll get this merged too once the conflicts are sorted.

**Comment by graingert** [comment]
@glenjamin I've switched to eslint:recommended for now.

**Comment by graingert** [comment]
@glenjamin 

> Can you remove the lint step from npm test and instead add it as a separate line item on travis? I'd rather they both always ran.

I've used npm-run-all to make sure they all run.

**Pull request merged**
