### PR TITLE
Load reporters from file when setup includes mocha-multi=filename

### PR DESCRIPTION
**Pull request by ShadSterling**
Load reporters from file when setup includes `mocha-multi=filename`

### CODE REVIEW

**Comment by glenjamin** [comment]
I'm not really clear what this is doing.

Could you add some docs and tests, and provide some context in the PR description for what this does and why please?

**Comment by ShadSterling** [comment]
The gist is to load reporters and their configurations from a file.  So I don't have to prefix the command with a zillion environment variables to configure the reporters.

**Comment by ShadSterling** [comment]
When I clone to my computer and run lint it gives no errors.  What is Travis CI doing differently?

**Comment by ShadSterling** [comment]
Took a while to figure out how your verification script worked; I've added verification of loading one reporter from a file similar to the existing verifications.

**Comment by glenjamin** [comment]
Can you give some scenarios where this would be used?

The usual approach to this I've seen is to encode the configuration list into a bash script or the config of the task runner which is executing the tests - which don't require any changes to the existing code.

**Comment by ShadSterling** [comment]
I just found it dumbfounding that it wasn't possible to use a config file.  I couldn't use mocha-multi-reporters because some reporters use stdout and can't be configured otherwise, but other reporters don't use their own config files and need multiple options specified.  I thought about allowing pairs of the form`reportername.optionname=value`, but this way seemed simpler.  Bash isn't readily available everywhere, and not all projects use a task runner (besides npm).  Why avoid allowing a config file?

**Comment by glenjamin** [comment]
Ah, so the crux of the issue is that there’s no other way to pass reporter options to the individual reporters using the environment variable?

**Comment by glenjamin** [comment]
Mocha itself can already be configured via a config file - `mocha.opts`, which is one of the reasons i’d rather not add yet another config file & the associated code to load it.

If there was a way to pass the full deep config object as a command line flag which worked in `mocha.opts`, would that satisfy the need?

**Comment by ShadSterling** [comment]
You mean there's already a mocha config file where I can put the same information and have it work essentially like my patch?  Where is that documented?

I don't really care about the command line options, I care about passing options to reporters and still capturing their stdout.  For consistency with every other tool, I'd rather do that in a json file, and not have to do more with command line options than name that file.

**Comment by glenjamin** [comment]
There’s already a mocha config file that can be used to pass any options which are available on the command line: https://mochajs.org/#mochaopts

It isn’t currently possible to pass the reporter options in as JSON, but I think it should be made possible. Without this you can’t pass options to the inner reporters.

This would be a variation on your PR, or a new one.

I like the approach of using `mocha-multi=` in reporter-options, but if this could accept the JSON instead of a filenane I think it would be usable in more scenarios.

Although the more I think about this, the more i’m warming to your original config file proposal

**Comment by ShadSterling** [comment]
Yeah, it wasn't my first thought either but it seemed like the most compatible.  I don't see any other use for `mocha-multi=`, and trying to enter JSON directly where you can't use `,`s would require some awkward encoding.

**Pull request merged**
