### PR TITLE
refactor process exit interceptor

### LINKED ISSUE #11: Exit code is always 0
Given a simple setup:
```
multi="progress=-" mocha --reporter mocha-multi
```
Always return zero exit code, even tests has been failed. Library versions:
```
   "mocha": "2.3.2",
   "mocha-multi": "0.7.1",
```

I guess it happens because visionmedia/mocha#1059 already merged and some hacks doesn't necessary anymore. I could remove them by myself, but I am not sure, which parts of hacks actually still needed.

### PR DESCRIPTION
**Pull request by just-boris**
* patch process.exit only if we have streams needed to be flushed before exit
* preserve exit code while awaiting streams

closes #11

### CODE REVIEW

**Comment by just-boris** [comment]
Also, note that verify on markdown reporter is failing because of https://github.com/mochajs/mocha/issues/1875

**Comment by glenjamin** [comment]
Looks like mocha 2.3.3 is almost released which will fix that markdown issue. Going to wait for that to get a green build and merge this.

**Comment by just-boris** [comment]
@glenjamin done, build is passing now

**Comment by glenjamin** [comment]
Released as `v0.7.3`

**Comment by just-boris** [comment]
Thanks!

**Pull request merged**
