### PR TITLE
properly set exit code

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by glenjamin** [comment]
Is there a a description of the bug this fixes?

Is the issue present in the released code, or just in master?

**Comment by graingert** [comment]
@glenjamin any update on this?

**Comment by graingert** [comment]
@glenjamin any update on this?

**Comment by glenjamin** [comment]
Sorry, been a bit stacked at work recently but hoping to get time to look at OSS more over the holidays

**Comment by graingert** [comment]
@glenjamin been using this from github and it works well.

**Comment by graingert** [comment]
> Sorry, been a bit stacked at work recently but hoping to get time to look at OSS more over the holidays

any luck, @glenjamin ?

**Comment by graingert** [comment]
@glenjamin any update on this?

**Comment by glenjamin** [comment]
Sorry about all the delays, I expanded the testsuite to cover this case and confirmed that this fix does the job.

Releasing now as 1.0

**Pull request merged**
